

const audioList = [
  { text: "21:50", src: "01_Nieco-Okolo20-1-50" },
  { text: "Už len čakáme", src: "01_uz_len_cakame" },
  { text: "Bude príbeh nejaký", src: "02_bude_pribeh" },
  { text: "Dym šiel do kolmice", src: "03_Dym-Sel" },
  { text: "DŘŽCH DŘŽCH", src: "04_Dzrch-Dzrch" },
  { text: "Tak počkáme, nie?", src: "05_Tak-Pockame-Nie" },
  { text: "Strašne ťažký človek", src: "06_strasne_tezky_clovek" },
  { text: "Však on skolabuje", src: "07_Hovorim-Vsak-On-Zkolabuje" },
  { text: "Pripravené veci", src: "08_Pripravene-Veci" },
  { text: "Presne akurát polnoc", src: "10_Presne-Akorat-Polnoc" },
  { text: "Však on nie je viditeľný", src: "11_Vsak-On-Nie-Je-Viditelny" },
  { text: "Srdce-ventilátor", src: "12_Srdce-Ventilator-Trwwwuuu" },
  { text: "1, 2, 3, 4", src: "13_1-2-3-4" },
  { text: "A vtedy to prišlo", src: "14_V-Tedy-To-Prislo" },
  { text: "Útočný pokrik", src: "15_Na-Plnu-Palbu-Utocny-Pokrik-Haaaaaaa" },
  { text: "Chro Chro", src: "16_Chro-Chro" },
  { text: "Zver stíchla", src: "17_Zver-Stichla" },
  { text: "Toto už je koniec", src: "18_hovorim-toto-uz-je-konec" },
  { text: "Toto je čo? Lesný duch?", src: "19_Toto-Je-Co--Lesni-Duch-Bukovec-Kosice-Alebo-Co-To-Je" },
  { text: "Útok", src: "20_Utok" },
  { text: "Delobuch", src: "21_Delobuch" },
  { text: "Ako by ma zhypnotizoval", src: "22_Hypnoza" },
  { text: "Výbuch", src: "23_Vsch-Vsch-Vsch-Vsch" },
  { text: "Utiekol", src: "24_Uz-Utiekol-Uz-Nenie-Tu" },
  { text: "Neviditeľný démon", src: "07_neviditelny_demon" },
  { text: "Predátor", src: "07_predator" },
  { text: "Zošalel!", src: "26_ZOSALEL" },
  { text: "Rozrúcaj tu tie klobásy!", src: "27_TU-ROZRUCAJ-TU-TE-KLOBASY" },
  { text: "Nedalo sa prejsť", src: "28_Isli-Jsme-Hore" },
  { text: "JA PREJDEM!", src: "29_Ja-Prejdem" },
  { text: "Ani pivo nechcel", src: "30_To-On-Ani-Pivo-Nechcel" },
  { text: "Liter mlieka", src: "31_Litr-Mleka" },
  { text: "Civilizácia", src: "32_Aaa-Civilizaacia" },
  { text: "Tebe dobre jeblo", src: "33_Ty-Kokot-Teba-Dobre-Jeblo" },
];

export default audioList;
